/* ============================================================
   AskCommon knowledge base — short, factual chunks pulled
   directly from the Cancer in the Commonwealth curriculum
   (Modules 1-3), used to ground the assistant's answers and
   point students back to the right module. Server-side only:
   never shipped to the browser.
   ============================================================ */

const KB = [
  {
    id: "basics-mutation",
    module: "module1",
    title: "How cancer starts",
    keywords: ["cancer", "start", "cause", "dna", "mutation", "cell", "divide", "division", "what is cancer"],
    text: "Cancer is a disease of cells dividing when they shouldn't. Every cell carries DNA instructions for when to grow, divide, and die. A mutation (a change in that DNA) can damage a cell's normal 'off switches,' so the damaged cell survives and divides anyway. As abnormal cells keep dividing, they build up into a mass of tissue called a tumor. Not every tumor is cancer — see benign vs. malignant.",
  },
  {
    id: "basics-age",
    module: "module1",
    title: "Why age is the biggest risk factor",
    keywords: ["age", "old", "older", "elderly", "aging", "biggest risk factor"],
    text: "Advancing age is the single most significant risk factor for cancer. Every time a cell divides it has to copy its entire DNA, and copying isn't perfect. Over a longer lifetime, cells go through far more divisions, so there's more opportunity for copying errors (mutations) to build up. About one in four new cancer cases are diagnosed in people ages 65-74.",
  },
  {
    id: "benign-malignant",
    module: "module1",
    title: "Benign vs. malignant tumors",
    keywords: ["benign", "malignant", "tumor", "cancerous", "noncancerous"],
    text: "Benign tumors are usually small, slow-growing, non-invasive, not cancerous, and can't metastasize (spread). Malignant tumors are often large, fast-growing, invasive, cancerous, and can metastasize to other parts of the body. By definition, benign tumors don't invade nearby tissue or spread — that's the defining feature that separates them from malignant (cancerous) tumors.",
  },
  {
    id: "metastasis",
    module: "module1",
    title: "What is metastasis?",
    keywords: ["metastasis", "metastasize", "spread", "travel", "bloodstream", "lymph"],
    text: "Metastasis is when cancer cells break away from where they started and travel — usually through the bloodstream or lymphatic system — to another part of the body. Even after spreading, the cancer keeps the name of where it started (for example, breast cancer that spreads to the lungs is still called metastatic breast cancer, not lung cancer).",
  },
  {
    id: "cancer-types",
    module: "module1",
    title: "How many types of cancer are there?",
    keywords: ["types", "kinds", "how many", "carcinoma", "leukemia", "melanoma"],
    text: "Cancer isn't one disease — it's a category covering well over 100 different diseases. Most are named for the organ or tissue where they form, and some are named for the type of cell involved (for example, carcinoma, leukemia, and melanoma all describe cancers that start in particular cell types).",
  },
  {
    id: "diagnosis-process",
    module: "module1",
    title: "How cancer is diagnosed",
    keywords: ["diagnose", "diagnosis", "biopsy", "detect", "screening", "test", "found"],
    text: "Cancer is usually diagnosed in three steps: (1) something is noticed — a routine screening detects an abnormality, or a patient reports symptoms; (2) a biopsy is performed — a doctor removes a small sample of the tissue in question; (3) the sample is examined under a microscope for the physical characteristics of cancerous cells.",
  },
  {
    id: "disparities-ky",
    module: "module1",
    title: "Cancer rates in Kentucky",
    keywords: ["kentucky", "commonwealth", "state", "rates", "incidence", "mortality", "highest"],
    text: "Kentucky has the highest rate of new cancer cases (1st in incidence) of any state in the country, and ranks 2nd in the nation for cancer deaths (mortality). Within Kentucky, residents of Appalachian Kentucky are about 8% more likely to die from a preventable cancer than people living outside Appalachia — driven mainly by lifestyle habits, healthcare access, and education/income levels, not biology.",
  },
  {
    id: "disparities-race",
    module: "module1",
    title: "Cancer and race in the U.S.",
    keywords: ["race", "black", "disparity", "disparities", "african american"],
    text: "In the United States, Black populations have the highest rates of new cancer cases and the highest number of cancer deaths of any racial group. Researchers point to a combination of factors: genetics, healthcare inequities, delayed care due to past experiences of racism in the healthcare system, unequal access to state-of-the-art care, underrepresentation in research, and socioeconomic factors.",
  },
  {
    id: "riskfactor-age",
    module: "module2",
    title: "Risk factor: Age",
    keywords: ["age", "risk factor"],
    text: "Advancing age is the most significant risk factor for cancer — about one in four new cases are in people 65-74. DNA mutations tend to increase with age simply because cells have divided (and copied their DNA) more times. Kentucky connection: the average age in Appalachian Kentucky is about 40.9, relatively young, which is why this course focuses on the risk factors people CAN influence.",
  },
  {
    id: "riskfactor-alcohol",
    module: "module2",
    title: "Risk factor: Alcohol",
    keywords: ["alcohol", "drink", "drinking", "beer", "wine", "liquor"],
    text: "Drinking too much alcohol increases risk of mouth, throat, larynx, liver, and breast cancer. The type of alcohol doesn't matter — beer, wine, and liquor all contain ethanol, and it's the amount consumed that matters. Alcohol is an irritant that damages cells; mistakes made while repairing that damage can cause cancer-causing mutations. Kentucky ranks 17th in the nation for percentage of adults who drink excessively.",
  },
  {
    id: "riskfactor-immuno",
    module: "module2",
    title: "Risk factor: Immunosuppression",
    keywords: ["immune", "immunosuppression", "immunosuppressed", "transplant"],
    text: "People with underactive ('immunosuppressed') immune systems are more likely to develop cancer, because a weaker immune system is less able to detect and destroy cancer cells before they grow into tumors. People who've had an organ transplant and take immunosuppressive drugs (to prevent organ rejection) are at especially high risk.",
  },
  {
    id: "riskfactor-carcinogens",
    module: "module2",
    title: "Risk factor: Environmental carcinogens",
    keywords: ["carcinogen", "carcinogens", "pollution", "radon", "asbestos", "coal", "environment", "environmental"],
    text: "Long-term exposure to carcinogens like air pollution, radon, asbestos, engine exhaust, and heavy metals increases cancer risk — some directly cause DNA mutations, others make cells divide faster (raising the odds a mutation occurs). Kentucky connection: coal is an important industry in the state, but too much exposure to coal-related substances can raise the risk of a harmful mutation.",
  },
  {
    id: "riskfactor-hormones",
    module: "module2",
    title: "Risk factor: Hormones",
    keywords: ["hormone", "hormones", "estrogen", "progesterone", "hormone replacement"],
    text: "Increased levels of estrogen and progesterone raise a woman's risk of breast cancer; women on hormone replacement therapy are at especially high risk. Higher hormone levels can speed up how often cells multiply, raising the odds a DNA mutation occurs.",
  },
  {
    id: "riskfactor-obesity",
    module: "module2",
    title: "Risk factor: Obesity",
    keywords: ["obesity", "obese", "overweight", "weight", "bmi"],
    text: "Being significantly overweight raises risk for cancers of the breast, colon, rectum, endometrium, esophagus, kidney, pancreas, gallbladder, and others. Excess fat can trigger long-term inflammation that damages cells; high insulin levels common with obesity can stimulate cell division and suppress normal cell death, both favoring tumor growth. Kentucky has the 10th-highest obesity rate in the country, about 41% of adults.",
  },
  {
    id: "riskfactor-radiation",
    module: "module2",
    title: "Risk factor: Radiation",
    keywords: ["radiation", "x-ray", "xray", "gamma", "neutron"],
    text: "Excessive exposure to radiation — including X-rays, gamma rays, and neutrons — increases cancer risk because radiation damages DNA, creating mutations that can lead to cancer. This is why patients getting X-rays wear a lead vest, which reduces radiation reaching the rest of the body.",
  },
  {
    id: "riskfactor-sun",
    module: "module2",
    title: "Risk factor: Excessive sun exposure",
    keywords: ["sun", "sunburn", "uv", "tanning", "tanning bed", "skin cancer", "melanoma"],
    text: "Too much ultraviolet (UV) light exposure — from sunlight or artificial sources like tanning beds — increases cancer risk because UV rays damage skin cells, causing mutations that lead to uncontrolled cell division. Kentucky connection: it's common for farmers and other outdoor workers in Kentucky to skip sunscreen during long workdays, increasing cumulative UV exposure over time.",
  },
  {
    id: "riskfactor-tobacco",
    module: "module2",
    title: "Risk factor: Tobacco",
    keywords: ["tobacco", "smoke", "smoking", "cigarette", "vape", "vaping", "chew", "chewing"],
    text: "Tobacco use is a leading cause of cancer and of death from cancer. Smokers are regularly exposed to tobacco smoke chemicals; people who live around smokers are exposed to secondhand smoke; smokeless (chewing) tobacco raises risk of mouth and esophagus cancers. Tobacco products contain many chemicals that damage DNA. Kentucky connection: about 19.6% of Kentucky adults smoke (4th highest in the nation), 5.3% of high school students smoke, and 19.7% of high school students vape.",
  },
  {
    id: "riskfactor-infectious",
    module: "module2",
    title: "Risk factor: Infectious disease",
    keywords: ["virus", "viruses", "hpv", "hepatitis", "hiv", "epstein-barr", "infection", "infectious"],
    text: "Certain viruses, bacteria, and parasites raise cancer risk, including Epstein-Barr virus, hepatitis, HIV, and HPV. Some viruses disrupt the signaling that controls cell division, causing uncontrolled growth; some weaken the immune system; some cause chronic inflammation that raises mutation risk. The HPV vaccine protects against the virus linked to several types of cancer.",
  },
  {
    id: "early-detection",
    module: "module3",
    title: "Why early detection matters",
    keywords: ["early detection", "screening", "stage", "survival", "catch early"],
    text: "Early detection means cancer is found while it's still small, hasn't spread, and usually has few or no symptoms — achieved through regular screening tests. A small, localized cancer is generally far easier to treat successfully (sometimes with a single treatment like surgery) than a cancer that has already spread to multiple parts of the body.",
  },
  {
    id: "rural-access",
    module: "module3",
    title: "Rural healthcare access and cancer",
    keywords: ["rural", "appalachian", "access", "healthcare access", "barriers", "distance"],
    text: "Patients in rural areas are more likely to be diagnosed with later-stage cancers than patients in urban areas, often because of limited access to healthcare services. Barriers for rural Appalachian Kentucky residents include long distances to the nearest cancer care facility, difficult road conditions, and difficulty taking time off work to travel for care. A later-stage diagnosis can affect a patient's entire treatment plan.",
  },
  {
    id: "treatment-chemo",
    module: "module3",
    title: "Treatment: Chemotherapy",
    keywords: ["chemotherapy", "chemo", "drug", "drugs", "iv"],
    text: "Chemotherapy is one of the most common cancer treatments. It uses powerful chemical drugs to kill cancer cells — a single drug or multiple drugs, often infused through an IV. The drugs chosen depend on the tumor's size, the cancer's stage, the patient's age, and overall health.",
  },
  {
    id: "treatment-radiation",
    module: "module3",
    title: "Treatment: Radiation therapy",
    keywords: ["radiation therapy", "radiation treatment"],
    text: "Radiation therapy uses high doses of radiation (similar technology to an X-ray) to damage cancer cells' DNA, killing them and shrinking tumors. It doesn't work immediately — it can take days or weeks before cells begin to die, and cells keep dying even after treatment ends.",
  },
  {
    id: "treatment-surgery",
    module: "module3",
    title: "Treatment: Surgery",
    keywords: ["surgery", "surgeon", "operation", "remove tumor"],
    text: "Surgery removes the tumor from a specific part of the body, either entirely or partially. Doctors may remove only part of a tumor if removing all of it would damage another part of the body. Removing some or all of a tumor can also help other treatments work better and relieve pain or pressure.",
  },
  {
    id: "treatment-immuno",
    module: "module3",
    title: "Treatment: Immunotherapy",
    keywords: ["immunotherapy"],
    text: "Immunotherapy helps a patient's own immune system better recognize and fight cancer. It's less widely used than surgery, chemotherapy, or radiation, and can be given through an IV, as a pill, as a topical ointment, or inserted directly into the bladder for certain bladder cancers.",
  },
  {
    id: "treatment-stemcell",
    module: "module3",
    title: "Treatment: Stem cell transplant",
    keywords: ["stem cell", "stem cells", "transplant", "bone marrow"],
    text: "A stem cell transplant restores stem cells (young cells that can develop into nearly any cell type) in patients whose own stem cells were destroyed by chemotherapy or radiation. Steps: (1) stem cells are collected from a healthy donor or the patient beforehand; (2) chemo/radiation destroys the patient's damaged stem cells; (3) the patient receives the new stem cells through an IV, restoring their blood cell supply.",
  },
  {
    id: "treatment-targeted",
    module: "module3",
    title: "Treatment: Targeted therapy",
    keywords: ["targeted therapy"],
    text: "Targeted therapy aims at specific proteins that control how cancer cells grow, divide, and spread. Depending on the drug, it can help the immune system destroy cancer cells, stop cancer cells from growing, deliver cell-killing substances directly to cancer cells, or starve cancer cells of the hormones they need to grow.",
  },
  {
    id: "treatment-hormone",
    module: "module3",
    title: "Treatment: Hormone therapy",
    keywords: ["hormone therapy"],
    text: "Hormone therapy slows or stops growth of certain cancers by changing the hormones available to them. It's used to treat prostate or breast cancer specifically — cancers whose growth can be influenced by hormone levels.",
  },
  {
    id: "treatment-precision",
    module: "module3",
    title: "Treatment: Precision medicine",
    keywords: ["precision medicine", "genetic", "genetics", "personalized"],
    text: "With precision medicine, doctors choose treatment based on the genetic makeup of a patient's specific tumor. Patients whose tumors share a targetable genetic change receive one type of treatment, while patients with a different genetic change receive a different one — this only works if there's an existing drug that can target that specific genetic change.",
  },
  {
    id: "site-help",
    module: "meta",
    title: "About this course and site",
    keywords: ["certificate", "module", "modules", "progress", "quiz", "risk calculator"],
    text: "This course has three self-paced modules: Module 1 (Cancer Basics & Health Disparities), Module 2 (Risk Factors & Modifiable Behaviors), and Module 3 (Diagnosis & Treatment). Each module unlocks the next after its quiz is completed. Finishing a module's post-test unlocks a printable certificate on the Certificates page. There's also a Risk Calculator page with an educational (not diagnostic) risk estimate based on lifestyle questions. Progress is saved in the browser on that device.",
  },
];

module.exports = { KB };
